### ISSUE TITLE
Error loading css file

### ISSUE THREAD

**Issue by romaincazier** [eelke/ProcessPageListVersionsCounter#1]
Hi!

This is a very small bug but when you updated the css filename you forgot to update the path in the [`$config->styles->add`](https://github.com/eelke/ProcessPageListVersionsCounter/blob/e731c7ff126e4e58add01144699ea450d4e62eca/ProcessPageListVersionsCounter.module.php#L27).

For simplicity you could go with:
```php
$this->config->styles->add($this->config->urls->ProcessPageListVersionsCounter . "$this.css");
```

**Comment by eelke** [comment]
Thanks for the bug report @romaincazier, I replaced it with your code.
